#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Config that survives re-runs lives in .env.deploy (NON-secret only: ids, region, urls).
# Real secrets go straight to Secret Manager and are NEVER written to disk here.
ENV_FILE=".env.deploy"

SERVICE="kissflow-forge"

# gcp_secret NAME VALUE — create-or-add-version in Secret Manager. Idempotent.
gcp_secret() {
  local name="$1" value="$2"
  if gcloud secrets describe "$name" --project "$PROJECT" >/dev/null 2>&1; then
    printf '%s' "$value" | gcloud secrets versions add "$name" --data-file=- --project "$PROJECT" >/dev/null
  else
    printf '%s' "$value" | gcloud secrets create "$name" --data-file=- \
      --replication-policy=automatic --project "$PROJECT" >/dev/null
  fi
  printf '  %s✓ stored%s Secret Manager: %s\n' "$GREEN" "$RESET" "$name"
}

TOTAL_STAGES=6

banner "kissflow-forge → Cloud Run (Google OAuth)"

# ── Stage 1 · Preflight ───────────────────────────────────────────────────
stage "Preflight — tools, project, APIs"
say "This deploys the kissflow-forge MCP to Cloud Run, gated by Google OAuth (each Cowork"
say "user logs in with their org Google account). You must be logged in to gcloud first."
if ! command -v gcloud >/dev/null 2>&1; then
  warn "gcloud not found — install the Google Cloud SDK, then re-run."; exit 1
fi
step "If you are not logged in, run in another terminal:  gcloud auth login"
pause "Logged in to gcloud?"
ACTIVE_ACCOUNT=$(gcloud config get-value account 2>/dev/null)
note "active gcloud account: ${ACTIVE_ACCOUNT:-<none>}"
warn "This MUST be your org account (e.g. @cjexpress) with deploy rights — NOT a personal gmail."
if ! confirm "Is '${ACTIVE_ACCOUNT}' the right account?"; then
  say "Switch it, then re-run this wizard:"
  say "    gcloud auth login <your-org-account>"
  say "    gcloud config set account <your-org-account>"
  exit 1
fi
ask GCP_PROJECT "GCP project id:"
ask GCP_REGION  "Cloud Run region (e.g. asia-southeast1):"
PROJECT="$GCP_PROJECT"; REGION="$GCP_REGION"
write_env GCP_PROJECT "$GCP_PROJECT"
write_env GCP_REGION  "$GCP_REGION"
say "Enabling required APIs (run, cloudbuild, secretmanager, artifactregistry)…"
# Soft-fail: if your admin already enabled these and you only hold serviceUsageConsumer,
# you can't run 'enable' yourself — that's fine, keep going. A truly-off API surfaces at deploy.
gcloud services enable run.googleapis.com cloudbuild.googleapis.com \
  secretmanager.googleapis.com artifactregistry.googleapis.com --project "$PROJECT" \
  || warn "couldn't enable APIs (need serviceUsageAdmin, or have your admin enable them) — continuing"
PROJECT_NUMBER=$(gcloud projects describe "$PROJECT" --format='value(projectNumber)')
# Cloud Run's deterministic per-region URL — known BEFORE first deploy, so the OAuth redirect
# can be set in one pass. Verified against the real URL after deploy (Stage 5).
SERVER_BASE_URL="https://${SERVICE}-${PROJECT_NUMBER}.${REGION}.run.app"
write_env SERVER_BASE_URL "$SERVER_BASE_URL"
note "predicted service URL: $SERVER_BASE_URL"

# ── Stage 2 · Google OAuth client ─────────────────────────────────────────
stage "Google — OAuth consent + client ID"
say "Create the OAuth client claude.ai authenticates users against. Do this in the SAME"
say "GCP project you are deploying to. No Azure, no new account."
open_url "https://console.cloud.google.com/apis/credentials/consent?project=${PROJECT}"
step "OAuth consent screen → User type: INTERNAL (locks logins to your org domain) → Create."
note "  If INTERNAL is greyed out (no Workspace admin): pick EXTERNAL, and under 'Test users'"
note "  add every org email that will use this — testing mode allows up to 100 without review."
step "Fill app name + support email → Save (scopes/optional pages can stay default)."
open_url "https://console.cloud.google.com/apis/credentials?project=${PROJECT}"
step "Create credentials → OAuth client ID → Application type: Web application."
step "Name: kissflow-forge-mcp"
step "Under 'Authorized redirect URIs' → Add URI:"
say  "    ${BOLD}${SERVER_BASE_URL}/auth/callback${RESET}"
step "Create → copy the Client ID and Client secret from the dialog."
ask        GOOGLE_CLIENT_ID     "Google Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Google Client secret:"
write_env  GOOGLE_CLIENT_ID     "$GOOGLE_CLIENT_ID"
say "Optional app-level allowlist ON TOP of the domain lock: only these emails may call any"
say "tool. Leave BLANK to allow any org user who passes OAuth."
ask ALLOWED_EMAILS "ALLOWED_EMAILS (comma-separated, or blank):"
write_env ALLOWED_EMAILS "$ALLOWED_EMAILS"

# ── Stage 3 · Kissflow engine config ──────────────────────────────────────
stage "Kissflow — dev-tenant config + keys"
say "The MCP's OWN credentials to the Kissflow dev tenant. Keys go to Secret Manager;"
say "the domain/account/app ids are non-secret env."
warn "Domain MUST contain 'dev-' — the engine refuses any non-dev domain."
ask KF_DEV_DOMAIN     "KF_DEV_DOMAIN (e.g. dev-kissflow.example.com):"
ask KF_DEV_ACCOUNT_ID "KF_DEV_ACCOUNT_ID:"
ask KF_APP            "KF_APP (target application id — one deploy = one app):"
write_env KF_DEV_DOMAIN     "$KF_DEV_DOMAIN"
write_env KF_DEV_ACCOUNT_ID "$KF_DEV_ACCOUNT_ID"
write_env KF_APP            "$KF_APP"
ask_secret KF_DEV_ACCESS_KEY_ID     "KF_DEV_ACCESS_KEY_ID:"
ask_secret KF_DEV_ACCESS_KEY_SECRET "KF_DEV_ACCESS_KEY_SECRET:"

# ── Stage 4 · Secret Manager + IAM ────────────────────────────────────────
stage "GCP — store secrets + grant Cloud Run access"
say "Pushing secrets and granting the runtime service account read access."
gcp_secret google-client-secret      "$GOOGLE_CLIENT_SECRET"
gcp_secret kf-dev-access-key-id      "$KF_DEV_ACCESS_KEY_ID"
gcp_secret kf-dev-access-key-secret  "$KF_DEV_ACCESS_KEY_SECRET"
# Stable JWT signing key so server-issued tokens survive a restart/redeploy (no forced re-login).
MCP_JWT_SIGNING_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
gcp_secret mcp-jwt-signing-key       "$MCP_JWT_SIGNING_KEY"
RUNTIME_SA="${PROJECT_NUMBER}-compute@developer.gserviceaccount.com"
say "Ensuring the runtime SA (${RUNTIME_SA}) can read the secrets…"
# Best-effort: if the runtime SA already has project-level access (e.g. the default compute SA
# carries roles/editor, which includes secretmanager.versions.access) this is redundant, and
# a plain Editor deployer can't setIamPolicy on a secret anyway. So warn, don't abort — a real
# access gap surfaces loudly at container boot, not silently.
for s in google-client-secret kf-dev-access-key-id kf-dev-access-key-secret mcp-jwt-signing-key; do
  if gcloud secrets add-iam-policy-binding "$s" --project "$PROJECT" \
       --member "serviceAccount:${RUNTIME_SA}" --role roles/secretmanager.secretAccessor \
       >/dev/null 2>&1; then
    printf '  %s✓%s access → %s\n' "$GREEN" "$RESET" "$s"
  else
    note "  (skipped explicit binding on $s — SA likely already has project-level access)"
  fi
done

# ── Stage 5 · Deploy ──────────────────────────────────────────────────────
stage "Cloud Run — deploy"
say "Building from source and deploying. --allow-unauthenticated is CORRECT here:"
say "Cloud Run lets the request in at the infra layer; the GoogleProvider does the real"
say "OAuth gating at the app layer. --min-instances=1 + session affinity keep the OAuth"
say "session on one instance (the default token store is per-instance)."
confirm "Run 'gcloud run deploy $SERVICE --source .' now?" || { warn "skipped deploy"; finish; exit 0; }
gcloud run deploy "$SERVICE" --source . --project "$PROJECT" --region "$REGION" \
  --allow-unauthenticated --min-instances 1 --session-affinity --timeout 3600 \
  --set-env-vars "MCP_HTTP=1,KF_DEV_DOMAIN=${KF_DEV_DOMAIN},KF_DEV_ACCOUNT_ID=${KF_DEV_ACCOUNT_ID},KF_APP=${KF_APP},GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID},SERVER_BASE_URL=${SERVER_BASE_URL}" \
  --set-secrets "GOOGLE_CLIENT_SECRET=google-client-secret:latest,KF_DEV_ACCESS_KEY_ID=kf-dev-access-key-id:latest,KF_DEV_ACCESS_KEY_SECRET=kf-dev-access-key-secret:latest,MCP_JWT_SIGNING_KEY=mcp-jwt-signing-key:latest"
ACTUAL_URL=$(gcloud run services describe "$SERVICE" --project "$PROJECT" --region "$REGION" \
  --format='value(status.url)')
note "predicted: $SERVER_BASE_URL"
note "actual:    $ACTUAL_URL"
if [[ "$ACTUAL_URL" != "$SERVER_BASE_URL" ]]; then
  warn "URL differs from prediction — redeploying with the real URL, and you must ADD"
  warn "${ACTUAL_URL}/auth/callback as a redirect URI on the OAuth client (Stage 2)."
  SERVER_BASE_URL="$ACTUAL_URL"; write_env SERVER_BASE_URL "$SERVER_BASE_URL"
  gcloud run services update "$SERVICE" --project "$PROJECT" --region "$REGION" \
    --update-env-vars "SERVER_BASE_URL=${SERVER_BASE_URL}"
fi
say "Deployed at: ${BOLD}${SERVER_BASE_URL}${RESET}"
# ALLOWED_EMAILS holds commas, which would break --set-env-vars' own comma delimiter, so it
# rides in as its own update with a custom '@' delimiter. Empty = allow any org user.
if [[ -n "${ALLOWED_EMAILS:-}" ]]; then
  gcloud run services update "$SERVICE" --project "$PROJECT" --region "$REGION" \
    --update-env-vars "^@^ALLOWED_EMAILS=${ALLOWED_EMAILS}"
  say "App-level allowlist active: ${ALLOWED_EMAILS}"
fi

# ── Stage 6 · Connect claude.ai ───────────────────────────────────────────
stage "claude.ai — add the connector"
say "The MCP endpoint is:"
say "    ${BOLD}${SERVER_BASE_URL}/mcp${RESET}"
open_url "https://claude.ai/settings/connectors"
step "Settings → Connectors → Add custom connector."
step "Name: kissflow-forge   ·   Remote MCP server URL: the /mcp URL above."
step "Leave OAuth Client ID / Secret BLANK — FastMCP self-registers (DCR)."
step "Add → Connect → sign in with your org Google account → Allow."
note "Smoke test: check discovery is live —"
note "    curl -s ${SERVER_BASE_URL}/.well-known/oauth-protected-resource | head"

finish
